[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
uskz_deviant = "EMjfHiSdDdUTxRJMUxnkS9mAVqWaKw8MktGLNKJ94Lnj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localNet"
wallet = "~/.config/solana/id.json"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
